### ISSUE TITLE
[tuify][giti] Remove the `-c` argument for `subcommand`

### ISSUE THREAD

**Issue by nazmulidris** [r3bl-org/r3bl-open-core#206]
Currently the giti command looks like this:

```fish
cd tuify
./run.nu install-giti
giti branch -c delete
```

> https://asciinema.org/a/14V8v3OKKYvDkUDkRFiMDsCNg

Is it possible to remove the `-c <subcommand>` portion and replace it w/ a string? Does clap support this? Maybe create an advanced clap tutorial from this as well.

> Related issue:
> - https://github.com/r3bl-org/r3bl-open-core/issues/207

**Comment by Harshil-Jani** [comment]
Oh well, I was going through the giti code and find out that there is a confusion when implementing the binary. 
We are saying that `long` : "command" and `short` : 'c' are the longhand and shorthand for the commands. Unless we pass them into the CLI, There is no way our binary is gonna interprete `giti branch delete` (without -c). But in case, We remove the `long` and `short` keywords then it takes in as a normal CLI subcommand and leads to our expected behaviour. 

https://github.com/r3bl-org/r3bl-open-core/blob/87f9969d635a2d6c5eda833818254075db9d96d5/tuify/src/bin/giti.rs#L148

**Comment by nazmulidris** [comment]
@Harshil-Jani Fantastic. 
@NadiaIdris So we can just drop the usage of both `long` : "command" and `short' : "c" and the sub-command `delete` should just work as expected!
